### PR TITLE
provide pubkey in session

### PR DESCRIPTION
**Pull request by aljazceru**

### CODE REVIEW

**Comment by aljazceru** [comment]
@TaprootFreak but why idoesthe token derived from pubkey, its just something random

the problem with moving it to verify is that it breakes the model for companies who don't enforce that. Within session its also where signature is provided so if you dont get the token on /verify then you can skip the pubkey on session. this way it gets to work for both models and you still get all the info needed

**Comment by TaprootFreak** [comment]
@aljazceru The text that is signed must be able to be specified by the provider. And it is unique for each user. This is mandatory in order to be able to use DFX.

**Comment by aljazceru** [comment]
@TaprootFreak of course, but this design enables exactly that

steps to auth
1) call /verify to get the token for signing by the provider (token is whatever the provider returns)
2) node signs the token 
3) node calls /session with necessary information (signature + pubkey) 
4) provider can verify that token X for session N matches signature S with pubkey P 

this way you know that the user owns the node

You only need the pubkey at /verify time if you want to have persistent token for the user but that is imho a problem because then anyway at any time can identify as the user if they get a hold of that signature. 

the purposed solution gets you the same thing -> knowing that account belongs to the user and you can still attach whatever identity you have about the user on the backend to it since you know if signature + pubkey match, its just a more secure implementation since the token is different every time. and at the same time it works for scenarios where you don't need to enforce that.

**Comment by TKone7** [comment]
Hey,
I think the zbase32 signature already contains the pubkey, so it's not strictly necessary to pass it again. It might however be a good idea to include it in case another signature scheme would be used.

**Pull request merged**
